-- 코드를 작성해주세요
SELECT YEAR(a.DIFFERENTIATION_DATE) as YEAR, (b.MAX_SIZE-a.SIZE_OF_COLONY) as YEAR_DEV, a.ID
FROM ECOLI_DATA a 
     INNER JOIN
     (SELECT YEAR(DIFFERENTIATION_DATE) as YEAR, MAX(SIZE_OF_COLONY) as MAX_SIZE
     FROM ECOLI_DATA
     GROUP BY YEAR) b
     ON YEAR(a.DIFFERENTIATION_DATE) = b.YEAR 
WHERE YEAR = b.YEAR
ORDER BY YEAR, YEAR_DEV ASC